name: Workflow Test

on:
  - push

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump Version & Push Tag
        id: semver
        uses: mathieudutour/github-tag-action@v5
        with:
          release_branches: main
          pre_release_branches: development
          github_token: ${{ secrets.GITHUB_TOKEN }}
