name: Workflow Test Repeat

on:
  - push

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump Version & Push Tag
        id: semver
        uses: boxcee/github-tag-action@prereleases
        with:
          release_branches: main
          pre_release_branches: development,hotfix
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Write Semver
        run: |-
          printf "%s" "${{ steps.semver.outputs.new_version }}" > semver.txt