name: Workflow Test

on:
  - push

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump Version & Push Tag
        id: semver
        uses: mathieudutour/github-tag-action@v5
        with:
          release_branches: main
          pre_release_branches: development,staging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.new_tag }}
          release_name: ${{ steps.semver.outputs.new_tag }}
          body: ${{ steps.semver.outputs.changelog }}
